### ISSUE TITLE
test运行完后没有结果存放在哪里？

### ISSUE THREAD

**Issue by ice-llz** [luanshiyinyang/ExpressionRecognition#1]
楼主您好，感谢您的分享
在我运行完test.py后，测试的是jaffe数据集，只显示了一个数字，那么具体的每个表情的准确率以及综合准确率并没有显示出来，请问是存放在哪里呢

**Comment by luanshiyinyang** [comment]
我这边设计的时候默认就是得到accuracy这个数据集上的metric，具体的分类别准确率需要自行添加
