### ISSUE TITLE
报错：ValueError: Could not open XXX.tflite。求大神指导

### ISSUE THREAD

**Issue by gugugu640** [luanshiyinyang/ExpressionRecognition#36]
具体报错：ValueError: Could not open 'd:\DSX\BS\RL2.0\FacialExpressionRecognition-master\src\blazeface\srlazeface\weights
ace_detection_front.tflite'.

**Comment by gzycongqi** [comment]
我也不确定，可能缺什么库吧，你去找源库呢，我也是fork别人的库

**Comment by gzycongqi** [comment]
意思就是文件名字不对，你要识别的文件，没改名字，建议仔细阅读代码注释和readme




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "luanshiyinyang/FacialExpressionRecognition"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月14日(星期二) 晚上9:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [luanshiyinyang/FacialExpressionRecognition] 报错：ValueError: Could not open XXX.tflite。求大神指导 (Issue #36)





 
Closed #36 as completed.

**Comment by gugugu640** [comment]
您好，我现在还想请教一个问题。人脸表情识别项目中，您写到：在jaffe和CK+数据集上经过5折交叉验证达到99%的准确率，这部分在代码中有体现吗？或者有什么图片。如有打扰，实在抱歉！期望您的回复



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月14日(周二) 晚上9:16
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [luanshiyinyang/FacialExpressionRecognition] 报错：ValueError: Could not open XXX.tflite。求大神指导 (Issue #36)




 意思就是文件名字不对，你要识别的文件，没改名字，建议仔细阅读代码注释和readme 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "luanshiyinyang/FacialExpressionRecognition"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2023年3月14日(星期二) 晚上9:11 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [luanshiyinyang/FacialExpressionRecognition] 报错：ValueError: Could not open XXX.tflite。求大神指导 (Issue #36) 
 
 
 
 
 
   
 Closed #36 as completed.
