### ISSUE TITLE
求指教！指定一个视频检测的问题

### ISSUE THREAD

**Issue by gugugu640** [luanshiyinyang/ExpressionRecognition#37]
1. 想问一下大家，当要检测指定视频的时候，是弹出一个框出来显示指定视频的人脸还是检测完了将视频保存到什么地方了？
2. 为什么openCV中capture.read()输出一直为False，读取不到视频。具体报错：cv2.error: OpenCV(3.4.4) C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:3784: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'。检查了视频路径没有问题

**Comment by yichangjianduan** [comment]
请问你的可以正常运行吗 想请问你一些问题
